apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    run: my-nginx
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    run: my-nginx
  type: NodePort